// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1xlRngMx8EjuEFJZVrmYSXRvyZMo_2cw',
    appId: '1:553640933129:web:57a721bc87ce59c7b205d8',
    messagingSenderId: '553640933129',
    projectId: 'gestion-rtm-2026',
    authDomain: 'gestion-rtm-2026.firebaseapp.com',
    storageBucket: 'gestion-rtm-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjaSRk24Hg2jWeRRV5KTdRV-tXw4FOdME',
    appId: '1:553640933129:android:261268fd3b0407b4b205d8',
    messagingSenderId: '553640933129',
    projectId: 'gestion-rtm-2026',
    storageBucket: 'gestion-rtm-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg8gakfQ9YaUa5T9g8KE9QMNNdtUvP4Ms',
    appId: '1:553640933129:ios:0f1113ed00b15b46b205d8',
    messagingSenderId: '553640933129',
    projectId: 'gestion-rtm-2026',
    storageBucket: 'gestion-rtm-2026.firebasestorage.app',
    iosBundleId: 'com.example.gestionRtm2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg8gakfQ9YaUa5T9g8KE9QMNNdtUvP4Ms',
    appId: '1:553640933129:ios:0f1113ed00b15b46b205d8',
    messagingSenderId: '553640933129',
    projectId: 'gestion-rtm-2026',
    storageBucket: 'gestion-rtm-2026.firebasestorage.app',
    iosBundleId: 'com.example.gestionRtm2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1xlRngMx8EjuEFJZVrmYSXRvyZMo_2cw',
    appId: '1:553640933129:web:fb2549e66140fe02b205d8',
    messagingSenderId: '553640933129',
    projectId: 'gestion-rtm-2026',
    authDomain: 'gestion-rtm-2026.firebaseapp.com',
    storageBucket: 'gestion-rtm-2026.firebasestorage.app',
  );
}
